# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11.7-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: applaudo
      POSTGRES_PASSWORD: Applaudo2020*
      POSTGRES_DB: admin-db
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.8
    restart: always
    ports:
      - 6379:6379
    volumes:
      - $HOME/docker/volumes/redis:/var/lib/redis
